Repository cs361fall2018/project-dixonallstars, pull requests merged in 2018-10, with the labels that each got.

#11 Fixed bugs with UI
  src/main/java/assets/game.js
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Ship.java
  src/main/java/cs361/battleships/models/Square.java
Labels: bug

#13 added a func and testfunc to test if a ship type has already been placed
  src/main/java/cs361/battleships/models/Board.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: bug

#24 Implements modals to show error and game over messages.
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement, feature

#23 Fixed issue with some ship placement clicks being unresponsive
  src/main/java/cs361/battleships/models/Game.java
Labels: bug

#25 is19 and other touchups
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement, feature

#27 Added button controls and new cursor when hovering over an attack
  src/main/java/assets/css/custom.css
  src/main/java/assets/css/target.cur
  src/main/java/assets/game.js
  src/main/java/views/ApplicationController/index.ftl.html
Labels: enhancement, feature

#37 Refactors ship class into parent with subclasses inheriting it for each type. Adds tests.
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/cs361/battleships/models/Battleship.java
  src/main/java/cs361/battleships/models/Destroyer.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/cs361/battleships/models/Minesweeper.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
  src/test/java/cs361/battleships/models/ResultTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: Refactor
