Repository cs361fall2018/project-dixonallstars, pull requests merged in 2018-11, with the labels that each got.

#38 Reese refactor
  src/main/java/cs361/battleships/models/Board.java
Labels: Refactor

#40 Implements captain's quarter functionality to the game
  src/main/java/cs361/battleships/models/Armor.java
  src/main/java/cs361/battleships/models/AttackStatus.java
  src/main/java/cs361/battleships/models/Battleship.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Destroyer.java
  src/main/java/cs361/battleships/models/Minesweeper.java
  src/main/java/cs361/battleships/models/Ship.java
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/ShipTest.java
Labels: enhancement, feature

#44 Is35
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/AttackGameAction.java
  src/main/java/cs361/battleships/models/AttackStatus.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: enhancement, feature

#45 Fixed bug with static vars
  src/main/java/cs361/battleships/models/Game.java
Labels: bug

#51 Is47
  src/main/java/cs361/battleships/models/Board.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: enhancement, feature

#53 Submarine and submerge option displayed
  src/main/java/assets/css/custom.css
  src/main/java/assets/game.js
  src/main/java/controllers/ApplicationController.java
  src/main/java/controllers/PlacementGameAction.java
  src/main/java/cs361/battleships/models/Board.java
  src/main/java/cs361/battleships/models/Game.java
  src/main/java/views/ApplicationController/index.ftl.html
  src/test/java/cs361/battleships/models/BoardTest.java
  src/test/java/cs361/battleships/models/GameTest.java
Labels: enhancement, feature

#55 Fixes a bug preventing the submarine from moving correctly.
  src/main/java/cs361/battleships/models/Board.java
  src/test/java/cs361/battleships/models/BoardTest.java
Labels: bug
